### ISSUE TITLE
Google Maps Api

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#3]
Hi

I get this exception   
       java.lang.IllegalStateException: google.api-key not set
            at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
            at net.sf.sprockets.google.Places$Params.format(Places.java:784)
            at net.sf.sprockets.google.LocalPlacesParams.format(LocalPlacesParams.java:107)
            at net.sf.sprockets.google.Places.predictions(Places.java:488)
            at net.sf.sprockets.google.Places.autocomplete(Places.java:341)
            at net.sf.sprockets.widget.GooglePlaceAutoComplete$PlaceAdapter$PlaceFilter.performFiltering(GooglePlaceAutoComplete.java:395)
            at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

But I have the `sprockets.xml` file in `src/app/sprockets.xml`. I already tried put it in `res/ sprockets.xml` and `res/xml/sprockets.xml`.

Where should I put it?

**Comment by danielgomezrico** [comment]
It have to be in `/src/app/src/resources`
